  # This is another secret that has its password hardcoded into the template (NOT RECOMMENDED)
Resources:
  rdsSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: techno-secrets-rds-credentials
      Description: This secret has a hardcoded password in SecretString (use GenerateSecretString instead)
      SecretString: '{"username":"dbadmin","password":"TechnoCloud2026!","dbname":"ordersdb","host":"techno-rds-rdsdbinstance-twqhlb6mq2nu.caf9dkfctprx.us-east-1.rds.amazonaws.com"}'
